server:
  port: ${CHAT_PORT}

spring:
  application:
    name: chat-service

  profiles:
    include: swagger

  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: ${MONGO_URI}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: true

user-service:
  url: ${USER_SERVICE_URL}

eureka:
  instance:
    prefer-ip-address: true
    hostname: chat-service
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}