server:
  port: 0

spring:
  application:
    name: chat-service

eureka:
  instance:
    prefer-ip-address: true
    hostname: chat-service
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
