jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  access-token:
    plus-hour: ${JWT_ACCESS_PLUS_HOUR}
  refresh-token:
    plus-hour: ${JWT_REFRESH_PLUS_HOUR}

spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${OAUTH_NAVER_CLIENT_ID}
            client-secret: ${OAUTH_NAVER_CLIENT_SECRET}
            redirect-uri: ${OAUTH_NAVER_REDIRECT_URL}
            authorization-grant-type: authorization_code
            scope: email, nickname, mobile

          google:
            client-name: google
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH_GOOGLE_REDIRECT_URL}
            authorization-grant-type: authorization_code
            scope: profile, email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
