springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/swagger-ui.html/swagger-config
    urls:
      - name: post-service
        url: /post-service/open-api/v3/api/docs
      - name: user-service
        url: /user-service/open-api/v3/api/docs
      - name: media-service
        url: /media-service/open-api/v3/api/docs