server:
  port: ${GATEWAY_PORT}

eureka:
  instance:
    prefer-ip-address: true
    hostname: gateway-service
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

spring:
  application:
    name: gateway-service

  profiles:
    include: auth, swagger

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
              filters:
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}

            - id: chat-service
              uri: lb://chat-service
              predicates:
                - Path=/chat-service/**
              filters:
                - RewritePath=/chat-service/(?<segment>.*), /$\{segment}

            - id: post-service
              uri: lb://post-service
              predicates:
                - Path=/post-service/**
              filters:
                - RewritePath=/post-service/(?<segment>.*), /$\{segment}

            - id: media-service
              uri: lb://media-service
              predicates:
                - Path=/media-service/**
              filters:
                - RewritePath=/media-service/(?<segment>.*), /$\{segment}

          globalcors:
            cors-configurations:
              '[/**]':
                # allowed-origins 가 '*' 인 경우 false
                allow-credentials: true
                allowed-origins:
                  - http://${SERVER_ADDRESS}
                allowed-methods:
                  - POST
                  - GET
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - '*'