springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: post-service
        url: /post-service/open-api/v3/api/docs
      - name: user-service
        url: /user-service/open-api/v3/api/docs
      - name: media-service
        url: /media-service/open-api/v3/api/docs

swagger:
  username: ${SWAGGER_USERNAME}
  password: ${SWAGGER_PASSWORD}