server:
  port: ${MEDIA_PORT}

spring:
  application:
    name: media-service

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

  profiles:
    include:
      swagger

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    prefer-ip-address: true
    hostname: media-service
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

file:
  upload-dir: ${FILE_UPLOAD_DIR}
  context-path: ${FILE_CONTEXT_PATH}

url:
  scheme: ${FILE_URL_SCHEME}
  host: ${FILE_URL_HOST}
  prefix: ${FILE_URL_PREFIX}